/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-05-19 05:25:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class generic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>generic</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/assets/css/main.css\" />\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resources/images/y_title_icon.ico\">\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"is-preload\">\n");
      out.write("\n");
      out.write("\t\t<!-- Wrapper -->\n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t<header id=\"header\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\" class=\"title\"><strong>개발자들의 모임</strong> <span class=\"extra\">Hello World🤪</span></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t<nav id=\"nav\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown\">Dropdown</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum dolor</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Magna phasellus</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Etiam dolore nisl</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">서브 메뉴</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum dolor</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Phasellus consequat</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Magna phasellus</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Etiam dolore nisl</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Veroeros feugiat</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Veroeros feugiat</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"generic\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"elements\">Elements</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Main -->\n");
      out.write("\t\t\t\t\t<div id=\"main\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Content -->\n");
      out.write("\t\t\t\t\t\t\t<section class=\"main\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"category\">In Depth</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Etiam feugiat tempus veroeros lorem</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image main\"><img src=\"images/pic04.jpg\" alt=\"\" /></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>In ut odio eu quam consectetur tristique nec non nisl. Maecenas porttitor vestibulum augue, nec sodales eros blandit non. Phasellus libero nibh, erat blandit, aliquet volutpat purus. Nullam pretium sed turpis lorem, ac congue orci. Donec pulvinar sagittis pellentesque. In ut odio eu quam consectetur tristique nec non nisl. Maecenas porttitor vestibulum augue, nec sodales eros blandit non. Vis accumsan feugiat adipiscing nisl amet adipiscing accumsan blandit accumsan sapien blandit ac amet faucibus aliquet placerat commodo. Interdum ante aliquet commodo accumsan vis phasellus adipiscing. Ornare a in lacinia. Vestibulum accumsan ac metus massa tempor. Accumsan in lacinia ornare massa amet. Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Magna commodo lobortis</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan commodo odio cubilia ac eu interdum placerat placerat arcu commodo lobortis adipiscing semper ornare pellentesque.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Erat condimentum</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Interdum ante aliquet commodo accumsan vis phasellus adipiscing. Ornare a in lacinia. Vestibulum accumsan ac metus massa tempor. Accumsan in lacinia ornare massa amet. Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan. Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan commodo odio cubilia ac eu interdum placerat placerat arcu commodo lobortis adipiscing.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet blandit adipiscing arcu ante.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Posts -->\n");
      out.write("\t\t\t\t\t\t\t<section class=\"main\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"posts\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic05.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Mauris vitae</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic06.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Dapibus nulla</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic07.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Dictum veroeros</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic08.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Lorem sed magna</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic09.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Vitae adipiscing</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic10.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><a href=\"#\">Aliquam phasellus</a></h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"meta\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>3 days ago</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"favorites\">2,174</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"comments\">1,423</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing amet sed aliquam veroeros etiam magna.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Full Story</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Sed vitae consequat</h2>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Ipsum dolor sit amet tempus adipiscing amet sed aliquam magna etiam magna feugiat cursus lorem nisi. Amet mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus etiam adipiscing amet sed aliquam veroeros etiam feugiat veroeros aliquam feugiat cursus lorem nisi. Ut mauris vitae mi dapibus nulla dictum. Ipsum dolor sit amet tempus adipiscing tempus.</p>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"icons style2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-youtube\"><span class=\"label\">YouTube</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fields\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Name\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"message\" id=\"message\" placeholder=\"Message\" rows=\"4\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" /></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t\t\t\t\t<p>&copy; Untitled. All rights reserved. Lorem ipsum dolor sit amet nullam.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
