-- 게시판 테이블 생성
CREATE SEQUENCE T_SEQ_BOARD;
CREATE TABLE T_BOARD (
	BNO NUMBER,
	TITLE VARCHAR(200) NOT NULL,
	CONTENT VARCHAR(3000) NOT NULL,
	WRITER VARCHAR(100) NOT NULL,
	NEWDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

ALTER TABLE T_BOARD ADD CONSTRAINT T_BOARD_PK PRIMARY KEY(BNO);

SELECT * FROM T_BOARD;

INSERT INTO T_BOARD
(BNO, TITLE, CONTENT, WRITER, NEWDATE, UPDATEDATE)
VALUES(T_SEQ_BOARD.NEXTVAL, 'home', '화려한 불빛들  그리고 바쁜 일상들  뒤에 숨겨진  초라한 너의 뒷모습과  하고 싶은 일 해야만 하는 일  사이에서 고민하는  너의 무거운 어깨를 위해  너의 발걸음이 들릴 때  웃으며 마중을 나가는 게  너에게 해줄 수 있는  나의 유일한 선물이었지 어디 아픈 덴 없니  많이 힘들었지  난 걱정 안 해도 돼  너만 괜찮으면 돼  가슴이 시릴 때  아무도 없을 땐  늘 여기로 오면 돼  어두운 방에서 홀로 누워  사랑하는 사람을  사랑할 수 없는 너를 위해  현실 속에 무너져 내리는 가슴을 잡고 또 길을 나서는 너를 위해 너의 발걸음이 들릴 때 웃으며 마중을 나가는 게 너에게 해줄 수 있는 나의 유일한 선물이었지 어디 아픈 덴 없니 많이 힘들었지 난 걱정 안 해도 돼 너만 괜찮으면 돼 가슴이 시릴 때 아무도 없을 땐 늘 여기로 오면 돼  여기로 오면 돼!!', '로이킴', SYSDATE, SYSDATE);

INSERT INTO T_BOARD (BNO, TITLE, CONTENT, WRITER)
(SELECT T_SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM T_BOARD);

----------
-- 댓글 테이블 추가
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	RNO NUMBER(10),
	BNO NUMBER(10) NOT NULL,
	REPLY VARCHAR2(1000) NOT NULL, -- 댓글 
	REPLYER VARCHAR2(100) NOT NULL, -- 작성자
	REPLYDATE DATE DEFAULT SYSDATE, -- 작성날짜 
	UPDATEDATE DATE DEFAULT SYSDATE -- 수정날짜
);

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY(RNO);
-- ALTER TABLE TBL_REPLY DROP CONSTRAINT FK_REPLY;

ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY FOREIGN KEY(BNO)
REFERENCES T_BOARD(BNO) ON DELETE CASCADE;

SELECT * FROM TBL_REPLY;

INSERT INTO TBL_REPLY (RNO, BNO, REPLY, REPLYER) VALUES (SEQ_REPLY.NEXTVAL, 1376250, '너무 좋은데용?!', '프로댓글러');
