-- 
CREATE SEQUENCE SEQ_BOARD;

DROP TABLE TBL_BOARD;
CREATE TABLE TBL_BOARD(
	BNO NUMBER(10),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(200) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY(BNO);

INSERT INTO TBL_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE)
VALUES(SEQ_BOARD.NEXTVAL, '육군 아미타이거!', '육군육군유꾼!!!', 'army', SYSDATE
);

SELECT * FROM TBL_BOARD ORDER BY BNO desc;


INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER)
(SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD);

SELECT /*+ INDEX_DESC(TBL_BOARD PK_BOARD) */ ROWNUM, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE 
			FROM TBL_BOARD;
			
		
SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE 
FROM 
	(SELECT /*+ INDEX_DESC(TBL_BOARD PK_BOARD) */ ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE 
	FROM TBL_BOARD 
	WHERE ROWNUM <= 20) 
WHERE RN > 10;


---------------------------
-- 댓글 테이블 추가
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	RNO NUMBER(10),
	BNO NUMBER(10) NOT NULL,
	REPLY VARCHAR2(1000) NOT NULL, -- 댓글 
	REPLYER VARCHAR2(100) NOT NULL, -- 작성자
	REPLYDATE DATE DEFAULT SYSDATE, -- 작성날짜 
	UPDATEDATE DATE DEFAULT SYSDATE -- 수정날짜
);

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY(RNO);
-- ALTER TABLE TBL_REPLY DROP CONSTRAINT FK_REPLY;

ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY FOREIGN KEY(BNO)
REFERENCES TBL_BOARD(BNO) ON DELETE CASCADE;

SELECT * FROM TBL_REPLY;

INSERT INTO TBL_REPLY (RNO, BNO, REPLY, REPLYER) VALUES (SEQ_REPLY.NEXTVAL, 1376250, '별로인데용?!', '프로댓글러');
